apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "* 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django
            image: docker.io/andrinho/django_app
            env:
            - name: SECRET_KEY
              value: REPLACE_ME
            - name: DATABASE_URL
              value: postgres://test_k8s:OwOtBep9Frut@192.168.0.18:8001/test_k8s
            command:
            - ./manage.py
            - clearsessions
          restartPolicy: OnFailure