apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/component: web
data:
  SECRET_KEY: REPLACE_ME
  DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@192.168.0.18:8001/test_k8s
  DEBUG: "True"
  ALLOWED_HOSTS: 127.0.0.1,localhost,star-burger.test